version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: your_postgres_password

  nodejs:
    image: node:latest
    ports:
      - "8080:8080"
    command: sh -c "npm install && node index.js"
    volumes:
      - /opt/helloworld/app:/app
    working_dir: '/app'
